id: A02BFD080
title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages of
  the Path Combined with Guru Yoga'
type: translation
pechas:
- ID1795537
- I2571C930
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:32:54.806711
  last_modified_at: 2023-01-04 12:32:54.806716
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  ID1795537/685C: '9548'
  I2571C930/18F1: '9548'
